const names = [
    "Sex Fort",
    "Glue is not a Power Tool",
    "Birthday Preparations",
    "Pork Pockets",
    "For the Things That I Left at Her House",
    "Iron Milk",
    "Blood and Cinnamon",
    "Wind and Children",
    "Drama Burgers",
    "The Obesity Epidemic",
    "Undig My Hole",
    "Hotbed of Sodomy",
    "Horizontal Marriage Dance",
    "Wokless",
    "Princess Dysentery",
    "Hot Soda",
    "Seahorse Seahell",
    "Glass Chicken",
    "Roadmap to Immortality",
    "Smile Pocket",
    "Fresh Feelings",
    "Flesh Vessel",
    "Action Zorb",
    "Diarrhea Wizard",
    "Pulsating Desire",
    "Wet with Fear",
    "Trapped in the House",
    "Typhoid Mary and Cholera Sue",
    "KlosettKrieg",
    "Turquoise Echo",
    "Real-time Tragedy",
    "Ethnic Cleansing in the Bathroom",
    "Suite Number 212",
    "The Portuguese Disease",
    "Swood",
    "Vertical Hunger",
    "You Can't Piss on Hospitality",
    "Lionel the Dog-Faced Boy",
    "Toilet Sweat",
    "Let the Dog Control Your Body",
    "Four Babies in a Trench Coat",
    "Open for Business",
    "Martha's Family Panic",
    "Static Dad",
    "Rachel Doesn't Need a Pair of Shoes",
    "Crab Tower",
    "Sleeves",
    "Seahenge",
    "Worried About the Beans",
    "Too Late",
    "Pistol Concealment Purses",
    "Deathweapon",
    "Satisfaction Chain",
    "Hungry Ghost",
    "Having Problems",
    "Look Behind You",
    "The Government",
    "Reptile Dysfunction",
    "Super Nanny",
    "Not Safe",
    "Kill Kill Kill Kill Die Die Die",
    "This Isn't So Hard",
    "What Kind of Name is Hitler, Anyway?",
    "Smiley's Good Teeth Puppet Theatre",
    "Cesium-137",
    "Accident with Wider Consequences",
    "General Sound Production Corporation",
    "Standing Right Before Your Eyes",
    "Human National Treasure",
    "Not Very Cute",
    "Spin Cycle",
    "Permanent Revolution",
    "New Democracy",
    "The Fifth Modernization",
    "Lenon Fragrance",
    "Plan R",
    "Fan Death",
    "Attic Fan Fanatic",
    "Jon, Nathan, and Jonathan",
    "Gentling",
    "Spayed",
    "Sparklemouth",
    "Entscheidungsproblem",
    "Toilet Money",
    "Super Digital",
    "Rocket Jizz",
    "Sewer Vampire",
    "Intercalary Chapter",
    "Life Without Lips",
    "Diabetes Guy",
    "The Other Woman",
    "Waiting to Die",
    "Delicious Little Tree",
    "Graveyard for the Unlucky",
    "Lurking in the Sink",
    "Unfinished Sandwich",
    "Burger Queen",
    "Sucking on the Sea",
    "Happy Bargain",
    "Bought a Keyboard",
    "Teesh",
    "æˆ˜ä¿˜è·³èˆž [zhanfu tiaowu] â€“ Prisoner Dance",
    "Pooping into the Computer",
    "Major Corporation",
    "Association of American Witches and Wizards",
    "WunderbÃ¤ume",
    "Transvaginal Mesh Failure",
    "Ian Brandon Something",
    "Ex Inferno",
    "FKEYS",
    "Nuclear Mishap",
    "More Money or Shut Up",
    "Chachi Hands",
    "An Orphan with a Disease",
    "The Body Police",
    "Canada's Revenge",
    "Sharp Kisses",
    "Sunken Bridges",
    "Computers",
    "CAT",
    "Happy Combination",
    "Military Shovel",
    "The Verge of Tears",
    "Total Disaster",
    "Ministry of Social Hygiene",
    "Pave the Rainforest",
    "Megabat",
    "BOLEYV",
    "Liberace's Ghost",
    "Sneak-Cat",
    "Witch's Horse",
    "Permanently Weird",
    "Husband Murder",
    "Bad Habits & Political Excitement",
    "howareyouiamfine.",
    "So Excited",
    "Can't Tell When You're Being Sarcastic",
    "White Blobby Mass",
    "Night Kitchen",
    "DUANE!",
    "Hat Wobble",
    "Cinnamon Ghoul",
    "Twinkly the Cat",
    "Clitasaurus",
    "Mechanical Americans",
    "Keshuijia",
    "Very Very Sexy Sexy",
    "Salon des Moches",
    "Beefy Rash",
    "Toxic for Reproduction",
    "Calculator Jones",
    "My Lesbian Friend",
    "++",
    "In Your/The Butt",
    "Electric Zoo",
    "Brain Universe",
    "Art Dreams",
    "Weekend Computer Party",
    "Sneaky Pete",
    "Free Cable",
    "The Foot",
    "Crunchy Radio",
    "Soggy Bottom",
    "Crazy House",
    "Science Hum",
    "The Real Property and Improvements Known as 2544 N. Colorado St.",
    "Flesh Mother",
    "Mr. Gonorrhea",
    "Gentlemen's Special Interest Film",
    "Homeless Beef",
    "Emotion Police",
    "Special Kind of Fat",
    "Sexually Vivacious",
    "Too Many Grahams",
    "Obedient Androids",
    "Special Biscuits",
    "The All-Swearing Eye",
    "World's Scariest Dentist",
    "Heap of Smelliness",
    "Jeans and Heroin",
    "Jealous Spasm",
    "Wizards in the Sewer",
    "Teledork",
    "Drugged Sleep",
    "Oh my P!",
    "Apple III",
    "blep",
    "The Future",
    "A Function of Time",
    "snigle",
    "Space Goat",
    "Reality of Television",
    "Leaky Christmas",
    "Stress Mouth",
    "Guitarbage",
    "Fuck Blanket",
    "Bad News From (Outer) Space",
    "Private Bathroom",
    "Beardwish",
    "Zortran 95",
    "Uncountably Smelly",
    "The Third Millennium",
    "Kleptocracy",
    "Murderous Gerbils",
    "Size Ten Chaos",
    "Synthesizer Crime",
    "Fat Time of Day",
    "Hillbilly Constellation",
    "Benereal Disease",
    "Computer Diseases",
    "Valley of the Ignorant",
    "Sigmoid Function",
    "Zpecial Relativity",
    "Euclidean Love",
    "The Mermaid Experience",
    "Two Easy",
    "Wheeled Suitcase",
    "Personal Space Invasion in the Men's Restroom",
    "Cunnilingus and Psychiatry",
    "Denger Zone",
    "Sexy Garbagemen",
    "Voodoo CanapÃ©",
    "Fat People Get Wet",
    "Eruptive Kisses",
    "Ordinary People Driving Buses",
    "Depraved Penguins",
    "Foreskin of a Suffragette",
    "Evil Wind",
    "Economics of Crime",
    "Moral Hazard",
    "Non-Euclidean Ham",
    "Pets or meat",
    "Floor Chicken",
    "Toilet Events",
    "Architectural Compromise",
    "Fatherboard",
    "Eatbeast",
    "Before Picture",
    "Syphilis and Pinball",
    "Infernal Box",
    "Pestering Satan",
    "Hitler's Brain",
    "Away With It",
    "Terrible Mistakes",
    "Plea Bargain",
    "Very Odd",
    "Folding Chair Riot",
    "Snakes and Magnets",
    "Differential Mayonnaise",
    "Non-Euclidean Ketchup",
    "Terminal Lifestyle",
    "Digital Puppets",
    "Unloading Screen",
    "Satellites and Their Beams",
    "Psychotropic Hayride",
    "Chapter 11",
    "Thinkpiece",
    "Positronic Brian",
    "Triangle of Shame",
    "Infinite Misery and Infinite Joy",
    "Fungible Emotions",
    "Degenerate Art",
    "Mach Five Child",
    "Sold Separately",
    "Non-Jewish",
    "Electric Snake",
    "Bad Noise",
    "Quietly",
    "The Gland",
    "About to Explode",
    "Too much, too much",
    "Brain Bubble",
    "Silent Majority",
    "Flep.",
    "Sphincted",
    "Time Fog",
    "Stop Them!",
    "Stabbed",
    "Turgid with Fear",
    "Concentrated Vindictiveness",
    "Sexless Gravity Well",
    "Woman-Googling",
    "$band_name",
    "Fully Insane",
    "Leaky Bedroom Disaster",
    "Extracurricular Sex",
    "Even in Wales",
    "Lost in Canada",
    "Uncle Susan",
    "Love Rectangle",
    "Mystery Slime",
    "Touch and Stay",
    "Brain Ache",
    "Collective Delusion",
    "Zebroid",
    "Land o' Cakes",
    "Rush Hour Knife Attack",
    "Sex Toilet",
    "Virtual Classroom",
    "Tech Support",
    "frump.",
    "Psychotropic Cheese",
    "Sausage Roulette",
    "Sudden Wealth Syndrome",
    "Tears and Violence",
    "Futurewife",
    "Disease Caused by Ghosts",
    "Double Vagina",
    "Extraordinary Penis",
    "Party Drug",
    "Meow Meow",
    "Triggered",
    "Unboxing",
    "Fully-Automated Luxury Communism",
    "Self-Cleaning Oven",
    "Chicken Window",
    "Desperate Kickstarter",
    "Timeshare Husband",
    "Punishment System",
    "Fancy Lamps",
    "Internet Condom",
    "bovverd",
    "Lesboid",
    "Soiled and Contaminated Mouth",
    "Mister Lesbian",
    "Me Too",
    "Fancy Government Lady",
    "A Fancy Pant",
    "A Very Funny Story",
    "Sex Pest",
    "Religious Machines",
    "Self-Esteem Engine",
    "Mobile Crying Machine",
    "Sexual Arithmetic",
    "Big Electric Bastard",
    "Airport",
    "Grief Thief",
    "Unlicensed Liar",
    "Nuclear Medicine",
    "Communication Rod",
    "Marxist Theory of Sex",
    "Funeral Strippers",
    "Eat Your Own Children",
    "Contempt for Advertising",
    "Special Kind of Violence",
    "Cruel Meat",
    "King of the Babies",
    "Wishful Thinking",
    "Confidence Fairy",
    "Big Hydraulic Hug",
    "2.5 Fondue Pots",
    "Uncle Mom",
    "Brain Lubricant",
    "Blueberry Napalm",
    "Puke People",
    "Germps",
    "Surface Tension",
    "Immortal Jellyfish",
    "Teacher's Petting Zoo",
    "Interportable",
    "Gentlemen Prefer Vaginal Intercourse",
    "Mommy Wishes She Was in France",
    "Christmas Kidnapping",
    "Sexual Machine",
    "Cube of Emotion",
    "Brain Funeral",
    "Electric Penguin",
    "Bessel Dysfunction",
    "CyberLibertarian",
    "Titanium Baby",
    "Compulsory Hospitality",
    "Temperate Deciduous Fever",
    "Quadratic Vote Buying",
    "Electrical Asbestos",
    "Anal Dilation",
    "Not Gay, Just Busy",
    "19th Century Television",
    "Sound Snob",
    "Brain Stain",
    "Emotional Incontinence",
    "Pathological Laughter",
    "Compulsory Love",
    "Human Doing",
    "Exponential Hangover",
    "Logarithmic Joy, Exponential Despair",
    "Scared Robots",
    "Collisional Cascade",
    "Kessler Syndrome",
    "Pity Party",
    "Space Orphan",
    "Princess Nincompoop",
    "Sexual Touching",
    "Sexual Timebomb",
    "Erotic Cakes",
    "Cyberhusband",
    "Tempura Tantrum",
    "Random Acts of Whimsy",
    "Aging Aluminum Fetus",
    "Pessimistic Bees",
    "Rational Dress Society",
    "Unidentified Amusing Creatures",
    "+",
    "Organs of Matrimonial Necessity",
    "Mirthquake",
    "NC-17 Sockpuppet Show",
    "Statistical Provocateur",
    "Dura Mater",
    "internetsnuffelaar",
    "Cardboard and Friendship",
    "Night Mayor",
    "Riemann Ineffable",
    "Fragrant Violation",
    "Amateur Sex Change",
    "Linear Bird-Stuffing Paradigm",
    "UNSPECIFIED DISORDER OF PENIS",
    "Intellectual Self-Defense",
    "Infinite Garbage Can",
    "Discopus",
    "Eigenvalues of Love",
    "Cosmopolitan Invasive Weed",
    "Cake-Kicker",
    "Cybervirgin",
    "Sexual Compromise",
    "Smart Alex",
    "Birthday Attack",
    "Divine Catheter",
    "The Beast that Ate Minnesota",
    "Very Serious Hashtag",
    "Child Bride and Father Groom",
    "ULTRAFRENCH",
    "Tears of Bravery",
    "The Irresistable Clapping Machine",
    "Post-Hoc Revisionism",
    "Forgotten Beef",
    "Catastrophic Forgetting in Neural Networks",
    "Dog of Wonder",
    "Intelligent Frosting",
    "Non-Newtonian Morality",
    "Jewish Susan",
    "Flashy Cat",
    "Sad Stop",
    "Sufficiently Accurate for Poetry",
    "Magical Meat in a Bone House",
    "Menstrual Euphemism",
    "Leftist Punching Discourse",
    "Let's Talk About Western Values",
    "Beauty Queen Garbage Collector",
    "Catastrophic Linear Pile-up",
    "Cake Guilt",
    "Mighty FÃ¼hrer of the Sausage People",
    "Impressionistic Word Decorations",
    "Digital Drugs",
    "Imaginary Canadian Pronoun Jail",
    "Deep Space Beeps",
    "Touch Guess Think Win",
    "Technotrash",
    "Radical Lesbian Nuns",
    "Master Death File",
    "Anti-Baby Marmalade",
    "Bad Kid Internet High School",
    "Alarming Regularity",
    "Three Word Conspiracy Theories",
    "Some Sort of In Between",
    "21st Century Mummy",
    "European Bog Bodies",
    "Quality Content",
    "Anything Green",
    "Love Letter to Linux",
    "A Normal Human Thing to Do",
    "Slightly Out of the Womb",
    "The Firefly Club",
    "If Mozart Doesn't Stop Them",
    "Colonial Revival Movement",
    "The Sunshine Gene",
    "Simplified Radical Form",
    "Chocolate with No Consequences",
    "rhetorical experience",
    "The Temptations of Belgium",
    "Seated Shark",
    "Consensual Gun Show",
    "The Joy-Destroying Logic Machine",
    "Menstrual Turmoil",
    "The Swampoodle Connection",
    "Revolving Restaurant",
    "The Veneer of Civilization",
    "Humanoid Stain",
    "Bungled Foreign Boob Job",
    "Indistinct Chinese Chatter",
    "Hunter S. Thompsonâ€™s Funerary Cannon",
    "Crock Potlet",
    "Buldingcat",
    "Nebraskan Car Fire",
    "The Terminal Sump",
    "Calm Sandwich",
    "The Poet And The Egg",
    "The Atmospheric Railway",
    "Electric Seance",
    "Vision Logic",
    "Nurse A.I.",
    "Flesh FaÃ§ade",
    "Psychedelic Labrador",
    "Turbocharged Vaginal Douche",
    "Post-Nasal Drip",
    "Damage Joy",
    "The Ultraviolet Catastrophe",
    "Necessary Miracles",
    "Peach Street Style",
    "Too Strange for Strangetown",
    "Coronavirus Radio",
    "Sugar Shaker",
    "A Jazz Moment",
    "Two Menominees",
    "Misbehaving Goats"
];

const keywords = [
    "nature",
    "mountains",
    "flowers",
    "flower",
    "forest",
    "water",
    "ocean",
    "landscape",
    "arizona",
    "travel",
    "monochrome",
    "outside",
    "fog",
    "road",
    "bar",
    "nikkor",
    "beach",
    "sky",
    "sunset",
    "blue",
    "night",
    "tree",
    "white",
    "green",
    "portrait",
    "art",
    "light",
    "snow",
    "dog",
    "sun",
    "moon",
    "clouds",
    "cat",
    "park",
    "winter",
    "street",
    "summer",
    "sea",
    "city",
    "trees",
    "yellow",
    "lake",
    "people",
    "bridge",
    "family",
    "bird" ,
    "river",
    "pink",
    "house",
    "car",
    "food",
    "bw",
    "old",
    "macro",
    "music",
    "new",
    "orange",
    "garden",
    "blackandwhite",
    "glacier",
    "ice",
    "beauty",
    "view",
    "summit",
    "colors",
    "range",
    "scenic",
    "sightseeing",
    "adventure",
    "hike",
    "trail",
    "natural",
    "wonder",
    "legends",
    "amazing",
    "hummingbird",
    "paris",
    "silhouette",
    "canon photo",
    "september",
    "autumn",
    "spring",
    "seascape",
    "greece",
    "europe",
    "italy",
    "tuscany",
    "unreal",
    "atmosphere",
    "industrial",
    "alone",
    "abandoned",
    "car",
    "spain",
    "waterfall",
    "madrid",
    "temple",
    "fall",
    "beautiful",
    "beach",
    "coast",
    "cliffs",
    "dawn",
    "drama",
    "glow",
    "purple",
    "rocks",
    "unesco",
    "flight",
    "fishing",
    "speed",
    "countryside",
    "essex",
    "astronomy",
    "nasa",
    "space",
    "galaxy",
    "telescope",
    "reflection",
    "boat",
    "canyon",
    "lightning",
    "rain",
    "toronto",
    "horses",
    "smoke",
    "washington",
    "dc",
    "puddle",
    "mosaic",
    "morning",
    "forests",
    "texture",
    "perspective",
    "composition",
    "tone",
    "mood",
    "outdoor",
    "england",
    "castle",
    "field",
    "grass",
    "vintage",
    "explored",
    "humanity",
    "afghanistan",
    "monument",
    "architecture",
    "renaissance",
    "fox",
    "wolf",
    "sand",
    "iceland",
    "ireland",
    "scotland",
    "iconic",
    "warm",
    "cold",
    "towers",
    "rural",
    "change",
    "fence",
    "farm",
    "farmland",
    "goth",
    "mist",
    "woodland",
    "moss",
    "portugal",
    "ivy",
    "elk",
    "stag",
];

// call from button
function submitForm() {
    const bandName = names[Math.floor(Math.random() * names.length)];
    const keyword = keywords[Math.floor(Math.random() * keywords.length)];
    $.getJSON(
        "http://api.flickr.com/services/feeds/photos_public.gne?jsoncallback=?",
        {
            tags: keyword,
            tagmode: "any",
            format: "json"
        },
        function(data) {
            const rnd = Math.floor(Math.random() * data.items.length);

            const imageUrl = data.items[rnd]['media']['m'].replace("_m", "_b");

            const canvas = document.getElementById('album-cover');
            const context = canvas.getContext('2d');
            const image = new Image();
            image.onload = function() {
                // Clear the canvas
                context.fillStyle = 'white';
                context.fillRect(0, 0, canvas.width, canvas.height);
                // Scale the image down to fit it on the canvas
                let scaleFactor = 1.0;
                if (image.width > canvas.width) {
                    scaleFactor = canvas.width / image.width;
                }
                if (image.height > canvas.height) {
                    scaleFactor = Math.max(scaleFactor, canvas.height / image.height);
                }
                console.log(`Image is ${image.width} x ${image.height}, scaling by ${scaleFactor}`);
                // Draw the image
                const scaledWidth = scaleFactor * image.width;
                const scaledHeight = scaleFactor * image.height;
                const imageX = Math.max(0, (canvas.width - scaledWidth) / 2);
                const imageY = Math.max(0, (canvas.height - scaledHeight) / 2);
                context.drawImage(image, imageX, imageY, scaledWidth, scaledHeight);
                // Render the text
                const fontSize = 30;
                const shadowOffsetX = 3;
                const shadowOffsetY = 2;
                context.font = `bold ${fontSize}px Helvetica, Arial, sans-serif`;
                const textWidth = context.measureText(bandName, 0.8*canvas.width).width;
                const textX = (canvas.width - textWidth) / 2;
                const textY = canvas.height - 3.5 * fontSize;
                // Draw the shadow first
                context.fillStyle = 'black';
                context.fillText(
                    bandName,
                    textX + shadowOffsetX,
                    textY + shadowOffsetY,
                    0.8*canvas.width
                );
                // Then render the actual text in white
                context.fillStyle = 'white';
                context.fillText(bandName, textX, textY, 0.8*canvas.width);
            };
            image.src = imageUrl;
        }
    );
}
